apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: skaffold-sbt
build:
  artifacts:
  - image: skaffold-sbt-app
    custom:
      buildCommand: sbt -v test skaffoldBuild
      dependencies:
        paths:
          - build.sbt
          - src/**
        ignore:
          - target/**
deploy:
  kubectl:
    manifests:
      - k8s/app.yaml
