---
apiVersion: v1
kind: Namespace
metadata:
  name: akka

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: akka
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: akka
  name: pod-read-access
subjects:
  - kind: User
    name: system:serviceaccount:akka:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  namespace: akka
  name: app
spec:
  ports:
    - name: app
      port: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: my-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: akka
  name: app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: app
          image: skaffold-sbt-app
          imagePullPolicy: Never
          ports:
            - name: app
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 8558
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              port: management
            initialDelaySeconds: 10
            failureThreshold: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            initialDelaySeconds: 20
            failureThreshold: 10
            periodSeconds: 3
          resources:
            limits:
              memory: 1024Mi
            requests:
              memory: 1024Mi
          env:
            - name: AKKA_CLUSTER_NODE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APP_HTTP_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APP_MANAGEMENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
